#ifndef QSPRITEANIM_GLOBAL_H
#define QSPRITEANIM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QSPRITEANIM_LIBRARY)
#  define QSPRITEANIMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QSPRITEANIMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QSPRITEANIM_GLOBAL_H
